obj-y += core.o pcf.o global_boost.o ontime.o energy.o init_util.o band.o multi_load.o load_balance.o
obj-y += service.o

obj-y += cpu_select.o energy_select.o
obj-$(CONFIG_SCHED_TUNE) += st_addon.o
obj-y += cpu_select.o energy_select.o
obj-$(CONFIG_CPU_FREQ_GOV_ENERGYSTEP) += energy_step.o
obj-$(CONFIG_SCHED_USE_FLUID_RT) += frt.o
obj-$(CONFIG_FREQVAR_TUNE) += freqvar_tune.o
obj-$(CONFIG_SCHED_PMU_CONT) += pmu_cont.o
